server.port=8082
spring.application.name=order-service

# OpenTelemetry - export traces, metrics, and logs to OTel Collector
otel.exporter.otlp.endpoint=http://localhost:4318
otel.exporter.otlp.protocol=http/protobuf

# Enable all 3 signals
otel.traces.exporter=otlp
otel.metrics.exporter=otlp
otel.logs.exporter=otlp

# Actuator - expose prometheus metrics endpoint
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=order-service
